---
- name: Install epel - yum
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install pip - yum
  yum:
    name: "{{ package_to_install }}"
    state: present
    enablerepo: epel
