---
- name: Show use_python3 variable
  debug:
    msg: "Use Python3: {{ use_python3 }}"

- name: Set package for python3
  set_fact:
    package_to_install: "python3-pip"
    pip_executable: "pip3"
  when: 
    - "{{ use_python3 | bool }}"
    - ansible_pkg_mgr == 'apt'

- name: Set package for python2
  set_fact:
    package_to_install: "python-pip"
    pip_executable: "pip2"
  when: "(not {{ use_python3 | bool }} or ansible_pkg_mgr == 'yum')"

- name: Detect pip installation
  stat: 
    path: "/usr/bin/{{ pip_executable }}"
  register: pip_installed

- name: Install on Apt based system
  include: install-apt.yml
  when: 
    - ansible_pkg_mgr == 'apt'
    - pip_installed.stat.exists == false

- name: Install on Yum based system
  include: install-yum.yml
  when:
    - ansible_pkg_mgr == 'yum'
    - pip_installed.stat.exists == false

- name: Upgrade pip with pip
  pip:
    name: pip
    state: latest
    executable: "{{ pip_executable }}"

- name: Install virtualenv
  pip:
    name: virtualenv
    state: present
    executable: "{{ pip_executable }}"
