---
- name: Detect pip installation
  stat: 
    path: /usr/bin/pip
  register: pip_installed

- name: Set package for python3
  set_fact:
    package_to_install: "python3-pip"
  when: python3

- name: Set package for python2
  set_fact:
    package_to_install: "python-pip"
  when: python3 is undefined or not python3

- name: Install on Apt based system
  include: install-apt.yml
  when: 
    - ansible_pkg_mgr == 'apt'
    - pip_installed.stat.exists == false

- name: Install on Yum based system
  include: install-yum.yml
  when:
    - ansible_pkg_mgr == 'yum'
    - pip_installed.stat.exists == false

- name: Upgrade pip with pip
  pip:
    name: pip
    state: latest

- name: Install virtualenv
  pip:
    name: virtualenv
    state: present
