---
- name: Detect pip installation
  stat: 
    path: /usr/bin/pip
  register: pip_installed

- name: Install on Apt based system
  include: install-apt.yml
  when: (ansible_os_family == 'Debian' and pip_installed.stat.exists == false)

- name: Install on Yum based system
  include: install-yum.yml
  when: (ansible_os_family == 'RedHat' and pip_installed.stat.exists == false)
